name: 03-Scan-Vulnerability

on:
  pull_request:
    types: [opened, synchronize, edited]

  workflow_dispatch:

jobs:
  Scan-Vulnerability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: projects

      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install clamav clamav-daemon

      - name: Scan for viruses
        run: |
          clamscan -r projects > clamav_report.txt

      - name: Upload ClamAV report
        uses: actions/upload-artifact@v4
        with:
          name: clamav-report
          path: clamav_report.txt
